name       : libsepol
version    : 20170804
release    : 1
source     :
    - https://github.com/SELinuxProject/selinux/archive/20170804.tar.gz : 43a156eef40d790f4a66c5006cdb140601f5f83cdb76d9e0b0516f7654af95b6
license    : LGPL-2.1
component  : security.library
summary    : SELinux Policy Library
patterns   :
    - devel: /usr/bin
description: |
    libsepol from SELinux project
build      : |
    %make -C libsepol SHLIBDIR=%libdir% LIBDIR=%libdir%
install    : |
    %make_install -C libsepol SHLIBDIR=$installdir/%libdir% LIBDIR=$installdir/%libdir%
